#http
version: "3.8"

services:
    app:
        image: ghcr.io/mahn-ke/availability-by-vincent:latest
        restart: unless-stopped
        ports:
            - "3123:3000"
        environment:
            - CALENDAR_URLS=${CALENDAR_URLS}
