#http
version: "3.8"

services:
    app:
        image: ghcr.io/mahn-ke/availability-by-vincent:latest@sha256:7856b21b4f74ee210e2991e33a0ba4ff1172eefc7301577990a02a045630ae2e
        restart: unless-stopped
        ports:
            - "3123:3000"
        environment:
            - CALENDAR_URLS=${CALENDAR_URLS}
