#http
version: "3.8"

services:
    app:
        image: ghcr.io/mahn-ke/availability-by-vincent:latest@sha256:b255af79cbab7dedfd0107b5359622e34396c6d4774486ecaa5986f26c64ae73
        restart: unless-stopped
        ports:
            - "3123:3000"
        environment:
            - CALENDAR_URLS=${CALENDAR_URLS}
